version: 2.1 
orbs:
  slack: circleci/slack@4.3.0 
 
commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1 

  notify_slack_pass:
    steps: 
      - slack/notify: 
          event: pass 
          template: basic_success_1
jobs:
  build_Deploy:
    machine: 
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - slack/notify:
          channel: C046129C9T6
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "1- *Build Started For ${CIRCLE_PROJECT_REPONAME} on ${CIRCLE_BRANCH} *\n*Installing AWS CLI on Build Server*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - run:
          name: "Installing AWS CLI"
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "2- *Installing Node Modules and Creating Build*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: pass
      - run: 
          name: "Installing Node Modules and Creating Build"
          command: cd ./ && npm install && npm run build
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Updating Bucket!*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: pass
      - run: 
          name: "Updating Bucket!"
          command: aws s3 sync ./build s3://gitactionsbucket
      
      - notify_slack_error
      - notify_slack_pass       
 
workflows:
  version: 2
  executeJobs:
    jobs:
      - build_Deploy 
