version: 2.1 
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build_Deploy:
    machine: 
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - slack/notify:
          color: "#42e2f4"
          message: "Build Started"
      - run:
          name: "Installing AWS CLI"
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: 
          name: "Installing Node Modules and Creating Build"
          command: cd ./ && npm install && npm run build
      - run: 
          name: "Updating Bucket!"
          command: aws s3 sync ./build s3://gitactionsbucket     
 
workflows:
  version: 2
  executeJobs:
    jobs:
      - build_Deploy 
