jobs:
  build_Deploy:
    machine: 
      image: ubuntu
    steps:
      - checkout
      - run:
          name: "Installing AWS CLI"
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./ && npm install && nom run build
      - run: aws s3 sync ./build s3://circlecibucker

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_Deploy